name = "leapack10000"
author = "lea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3d8ab9fccb456c05913e31829f49e3ece43fc8400a059f35492bb085ac4ebb6"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
