name = "leapack10000"
author = "lea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e73563e8501b1877d43b5635cc5a44a7df3eff0f2094bacc7837c4630cd625b2"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
