name = "leapack10000"
author = "lea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "159679f6abb5edb7d96459d6d4f9abb2f446929da527a7dbba29cd87f4f9ed0a"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
